export const newArrivals = [
    {
        id: 1,
        name: "Cordoba 45 Limited Spanish Classical Guitar Spruce/Ebony",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/newArrivals.images/group10.png",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 2,
        name: "Guitar brand and name 2",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/newArrivals.images/rectangle2.png",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 3,
        name: "Guitar brand and name 3",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/newArrivals.images/rectangle3.png",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 4,
        name: "Guitar brand and name 4",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/newArrivals.images/rectangle4.png",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 5,
        name: "Guitar brand and name 5",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/newArrivals.images/rectangle5.png",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 6,
        name: "Guitar brand and name 6",
        price: "$399.99",
        condition: "Excellent",
        image: "image",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
      {
        id: 7,
        name: "Guitar brand and name 7",
        price: "$399.99",
        condition: "Excellent",
        image: "image",
        Link: "/",
        backgroundcolor: "#F0F0F0",
      },
];
