export const guitar = [
  {
    id: 1,
    name: "Gibson LC Century of Progress 1933",
    category: "Classical Guitar",
    condition: "Excellent",
    price: 399.99,
    newprice: 999.99,
    review: {
      main: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected hum",
      list: [
        "Various versions have evolved over the years",
        "sometimes by accident",
        "Various versions have evolved",
        "as their default model text",
        "Various versions have evolved over as their default model text",
        "as their default model text",
        "Various versions have evolved over",
      ],
    },
    specification: {
      label: {
        Condition: "Condition",
        Brand: "Brand",
        Model: "Model",
        Finish: "Finish",
        Categories: "Categories",
        Year: "Year",
        Series: "Series",
        FretboardMaterial: "Fretboard Material",
        PickupConfiguration: "Pickup Configuration",
        ScaleLength: "Scale Length",
        BodyShape: "Body Shape",
        RightOrLeftHanded: "Right/Left Handed",
        NumberOfStrings: "Number Of Strings",
        NeckMaterial: "Neck Material",
        ColorFamily: "Color Family",
        ModelFamily: "Model Family",
        FinishStyle: "Finish Style",
        BodyType: "Body Type",
        OffsetBody: "Offset Body",
        Bridge_TailpieceType: "Bridge/Tailpiece Type",
        NeckConstruction: "Neck Construction",
        NumberofFrets: "Number Of Frets",
      },
      state: {
        Condition: "Excellent",
        Brand: "Brand name",
        Model: "Model name",
        Finish: "Competition Red",
        Categories: "Solid body",
        Year: "1971",
        Series: "Fender Vintage CBS Era",
        FretboardMaterial: "Rosewood",
        PickupConfiguration: "SS",
        ScaleLength: "24",
        BodyShape: "Double cutaway",
        RightOrLeftHanded: "Right handed",
        NumberOfStrings: "6-String",
        NeckMaterial: "Maple",
        ColorFamily: "Competition Red",
        ModelFamily: "Fender mustang",
        FinishStyle: "Gloss",
        BodyType: "Solid body",
        OffsetBody: "Offset body",
        Bridge_TailpieceType: "Tremolo Tailpiece",
        NeckConstruction: "Bolt-on",
        NumberofFrets: "22",
      },
    },

    image: [
      {
        image: "/src/images/classicalGuitar.images/image1.png",
      },
      {
        image: "/src/images/classicalGuitar.images/image2.png",
      },
      {
        image: "/src/images/classicalGuitar.images/image3.png",
      },
      {
        image: "/src/images/classicalGuitar.images/image4.png",
      },
      {
        image: "/src/images/classicalGuitar.images/image5.png",
      },
      {
        image: "/src/images/classicalGuitar.images/image6.png",
      },
    ],
  },
  {
    id: 2,
    name: "Cordoba 45 Limited Spanish Classical Guitar Spruce/Ebony",
    category: "Acoustic Guitar",
    condition: "Excellent",
    price: 299.99,
    newprice: 999.99,
    review: {
      main: "product 2",
      list: [
        "Various versions have evolved over the years",
        "sometimes by accident",
        "Various versions have evolved",
        "as their default model text",
        "Various versions have evolved over as their default model text",
        "as their default model text",
        "Various versions have evolved over",
      ],
    },
    specification: {
      label: {
        Condition: "Condition",
        Brand: "Brand",
        Model: "Model",
        Finish: "Finish",
        Categories: "Categories",
        Year: "Year",
        Series: "Series",
        FretboardMaterial: "Fretboard Material",
        PickupConfiguration: "Pickup Configuration",
        ScaleLength: "Scale Length",
        BodyShape: "Body Shape",
        RightOrLeftHanded: "Right/Left Handed",
        NumberOfStrings: "Number Of Strings",
        NeckMaterial: "Neck Material",
        ColorFamily: "Color Family",
        ModelFamily: "Model Family",
        FinishStyle: "Finish Style",
        BodyType: "Body Type",
        OffsetBody: "Offset Body",
        Bridge_TailpieceType: "Bridge/Tailpiece Type",
        NeckConstruction: "Neck Construction",
        NumberofFrets: "Number Of Frets",
      },
      state: {
        Condition: "Excellent",
        Brand: "Brand name",
        Model: "Model name",
        Finish: "Competition Red",
        Categories: "Solid body",
        Year: "1971",
        Series: "Cordoba 45 Limited Spanish Classical Guitar Spruce/Ebony",
        FretboardMaterial: "Rosewood",
        PickupConfiguration: "SS",
        ScaleLength: "24",
        BodyShape: "Double cutaway",
        RightOrLeftHanded: "Right handed",
        NumberOfStrings: "6-String",
        NeckMaterial: "Maple",
        ColorFamily: "Competition Red",
        ModelFamily: "Fender mustang",
        FinishStyle: "Gloss",
        BodyType: "Solid body",
        OffsetBody: "Offset body",
        Bridge_TailpieceType: "Tremolo Tailpiece",
        NeckConstruction: "Bolt-on",
        NumberofFrets: "22",
      },
    },

    image: [
      {
        image: "/src/images/classicalGuitar.images/example_image1.png",
      },
      {
        image: "/src/images/classicalGuitar.images/example_image2.png",
      },
      {
        image: "/src/images/classicalGuitar.images/example_image3.png",
      },
    ],
  },
  {
    id: 3,
    name: "Fender USA 2013 American Vintage '65 Jazzmaster",
    category: "Ukulele",
    condition: "Excellent",
    price: 199.99,
    newprice: 999.99,
    review: {
      main: "product 3",
      list: [
        "Various versions have evolved over the years",
        "sometimes by accident",
        "Various versions have evolved",
        "as their default model text",
        "Various versions have evolved over as their default model text",
        "as their default model text",
        "Various versions have evolved over",
      ],
    },
    specification: {
      label: {
        Condition: "Condition",
        Brand: "Brand",
        Model: "Model",
        Finish: "Finish",
        Categories: "Categories",
        Year: "Year",
        Series: "Series",
        FretboardMaterial: "Fretboard Material",
        PickupConfiguration: "Pickup Configuration",
        ScaleLength: "Scale Length",
        BodyShape: "Body Shape",
        RightOrLeftHanded: "Right/Left Handed",
        NumberOfStrings: "Number Of Strings",
        NeckMaterial: "Neck Material",
        ColorFamily: "Color Family",
        ModelFamily: "Model Family",
        FinishStyle: "Finish Style",
        BodyType: "Body Type",
        OffsetBody: "Offset Body",
        Bridge_TailpieceType: "Bridge/Tailpiece Type",
        NeckConstruction: "Neck Construction",
        NumberofFrets: "Number Of Frets",
      },
      state: {
        Condition: "Excellent",
        Brand: "Brand name",
        Model: "Model name",
        Finish: "Competition Red",
        Categories: "Solid body",
        Year: "1971",
        Series: "Fender USA 2013 American Vintage '65 Jazzmaster",
        FretboardMaterial: "Rosewood",
        PickupConfiguration: "SS",
        ScaleLength: "24",
        BodyShape: "Double cutaway",
        RightOrLeftHanded: "Right handed",
        NumberOfStrings: "6-String",
        NeckMaterial: "Maple",
        ColorFamily: "Competition Red",
        ModelFamily: "Fender mustang",
        FinishStyle: "Gloss",
        BodyType: "Solid body",
        OffsetBody: "Offset body",
        Bridge_TailpieceType: "Tremolo Tailpiece",
        NeckConstruction: "Bolt-on",
        NumberofFrets: "22",
      },
    },

    image: [
      {
        image: "/src/images/classicalGuitar.images/cart1.png",
      },
    ],
  },
];
