export const serviceItems = [
    {
      id: 1,
      name: "shipping",
      backgroundcolor: "#F0F0F0",
      title: "Free and Insured Shipping on Every Order",
      text: "",
      image: "/src/images/service.images/frame1.png",
      Link: "/",
    },
    {
      id: 2,
      name: "customerService",
      backgroundcolor: "#F0F0F0",
      title: "Expert Customer Service",
      text: "",
      image: "/src/images/service.images/frame2.png",
      Link: "/",
    },
    {
      id: 3,
      name: "pickUp",
      backgroundcolor: "#F0F0F0",
      title: "In-Store Pick Up",
      text: "We provide flexibility for you to pick up your guitars in person.",
      image: "/src/images/service.images/frame3.png",
      Link: "/",
    },
    {
      id: 4,
      name: "proSelection",
      backgroundcolor: "#F0F0F0",
      title: "Pro Selection on Each Guitar",
      text: "Our experts carefully review each guitar to guarantee you the quality.",
      image: "/src/images/service.images/frame4.png",
      Link: "/",
    },
  ];