export const serviceItems = [
    {
      id: 1,
      name: "shipping",
      backgroundcolor: "#F0F0F0",
      title: "Reliable Shipping",
      text: "We handle each order with care and use trusted delivery services.",
      image: "",
      Link: "/",
    },
    {
      id: 2,
      name: "customerService",
      backgroundcolor: "#F0F0F0",
      title: "Expert Customer Service",
      text: "We’re here to help with any questions about guitars, orders, or delivery.",
      image: "",
      Link: "/",
    },
    {
      id: 3,
      name: "pickUp",
      backgroundcolor: "#F0F0F0",
      title: "In-Store Pick Up",
      text: "We provide flexibility for you to pick up your guitars in person.",
      image: "",
      Link: "/",
    },
    {
      id: 4,
      name: "proSelection",
      backgroundcolor: "#F0F0F0",
      title: "Pro Selection on Each Guitar",
      text: "Our experts carefully review each guitar to guarantee you the quality.",
      image: "",
      Link: "/",
    },
  ];