export const featuredGuitars = [
    {
        id: 1,
        name: "Vintage 1960s Harmony Rocket H-59 Red Sunburst 3 PU 7/8 VG Condition Lots Of Knobs De Armond DeArmond Gold Foil Pick Ups",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/featuredGuitars.images/rectangle1.png",
        Link: "/",
      },
      {
        id: 2,
        name: "Epiphone Cortez FT45N 1966",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/featuredGuitars.images/rectangle2.png",
        Link: "/",
      },
      {
        id: 3,
        name: "Guitar brand and name 3",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/featuredGuitars.images/rectangle3.png",
        Link: "/",
      },
      {
        id: 4,
        name: "Guitar brand and name 4",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/featuredGuitars.images/rectangle4.png",
        Link: "/",
      },
      {
        id: 5,
        name: "Guitar brand and name 5",
        price: "$399.99",
        condition: "Excellent",
        image: "/src/images/featuredGuitars.images/rectangle5.png",
        Link: "/",
      },
      {
        id: 6,
        name: "Guitar brand and name 6",
        price: "$399.99",
        condition: "Excellent",
        image: "image",
        Link: "/",
      },
      {
        id: 7,
        name: "Guitar brand and name 7",
        price: "$399.99",
        condition: "Excellent",
        image: "image",
        Link: "/",
      },
];
